# Generated by Django 5.1.2 on 2024-11-16 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klassi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=50, verbose_name='nomi')),
                ('narxi', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='narxi')),
            ],
            options={
                'verbose_name': 'Klass',
                'verbose_name_plural': 'Klasslar',
            },
        ),
        migrations.CreateModel(
            name='Mehmonhona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=50, verbose_name='nomi')),
                ('stars', models.IntegerField()),
                ('narxi', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='narxi')),
            ],
            options={
                'verbose_name': 'Mehmonhona',
                'verbose_name_plural': 'Mehmonhonalar',
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=50, verbose_name='nomi')),
                ('izoh', models.CharField(max_length=500, verbose_name='izoh')),
                ('muddati', models.DateField(verbose_name='muddati')),
                ('narxi', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='narxi')),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.klassi', verbose_name='klass')),
                ('mehmonhona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.mehmonhona', verbose_name='mehmonhona')),
            ],
            options={
                'verbose_name': 'Sayohat',
                'verbose_name_plural': 'Sayohatlar',
            },
        ),
    ]
